
package calculadora;

public class interfaz extends javax.swing.JFrame {
    
    metodos rta = new metodos();
    
    public interfaz() {
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnRaiz = new javax.swing.JButton();
        txtsalida = new javax.swing.JLabel();
        Btn7 = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        txtsalidaop = new javax.swing.JLabel();
        BtnSuma = new javax.swing.JButton();
        BtnResta = new javax.swing.JButton();
        BtnIgual = new javax.swing.JButton();
        BtnDiv = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        Btnsen = new javax.swing.JButton();
        BtnMult = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        BtnVersion2 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        BtnPow = new javax.swing.JButton();
        Btntan = new javax.swing.JButton();
        Btncos = new javax.swing.JButton();
        BtnPunto1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        BtnRaiz.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnRaiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        BtnRaiz.setText("√");
        BtnRaiz.setBorder(null);
        BtnRaiz.setFocusPainted(false);
        BtnRaiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRaiz.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        BtnRaiz.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        BtnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRaizActionPerformed(evt);
            }
        });

        txtsalida.setBackground(new java.awt.Color(255, 255, 255));
        txtsalida.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtsalida.setForeground(new java.awt.Color(255, 255, 255));
        txtsalida.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtsalida.setBorder(new javax.swing.border.MatteBorder(null));
        txtsalida.setFocusable(false);
        txtsalida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Btn7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn7.setForeground(new java.awt.Color(255, 255, 255));
        Btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn7.setText("7");
        Btn7.setBorder(null);
        Btn7.setFocusPainted(false);
        Btn7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });

        Btn0.setBackground(new java.awt.Color(0, 0, 0));
        Btn0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn0.setForeground(new java.awt.Color(255, 255, 255));
        Btn0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn.png"))); // NOI18N
        Btn0.setText("0");
        Btn0.setBorder(null);
        Btn0.setFocusPainted(false);
        Btn0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn0.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn.png"))); // NOI18N
        Btn0.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn (1).png"))); // NOI18N
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });

        txtsalidaop.setBackground(new java.awt.Color(255, 255, 255));
        txtsalidaop.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtsalidaop.setForeground(new java.awt.Color(153, 153, 153));
        txtsalidaop.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtsalidaop.setBorder(new javax.swing.border.MatteBorder(null));
        txtsalidaop.setFocusable(false);
        txtsalidaop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BtnSuma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnSuma.setForeground(new java.awt.Color(255, 255, 255));
        BtnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn11.png"))); // NOI18N
        BtnSuma.setText("+");
        BtnSuma.setBorder(null);
        BtnSuma.setFocusPainted(false);
        BtnSuma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSuma.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn11.png"))); // NOI18N
        BtnSuma.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        BtnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSumaActionPerformed(evt);
            }
        });

        BtnResta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnResta.setForeground(new java.awt.Color(255, 255, 255));
        BtnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn11.png"))); // NOI18N
        BtnResta.setText("-");
        BtnResta.setBorder(null);
        BtnResta.setFocusPainted(false);
        BtnResta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnResta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn11.png"))); // NOI18N
        BtnResta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        BtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRestaActionPerformed(evt);
            }
        });

        BtnIgual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnIgual.setForeground(new java.awt.Color(255, 255, 255));
        BtnIgual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn11.png"))); // NOI18N
        BtnIgual.setText("=");
        BtnIgual.setBorder(null);
        BtnIgual.setFocusPainted(false);
        BtnIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnIgual.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn11.png"))); // NOI18N
        BtnIgual.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        BtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIgualActionPerformed(evt);
            }
        });

        BtnDiv.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnDiv.setForeground(new java.awt.Color(255, 255, 255));
        BtnDiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn11.png"))); // NOI18N
        BtnDiv.setText("/");
        BtnDiv.setBorder(null);
        BtnDiv.setFocusPainted(false);
        BtnDiv.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnDiv.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn11.png"))); // NOI18N
        BtnDiv.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        BtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDivActionPerformed(evt);
            }
        });

        BtnBorrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        BtnBorrar.setText("AC");
        BtnBorrar.setBorder(null);
        BtnBorrar.setFocusPainted(false);
        BtnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnBorrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        BtnBorrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });

        Btnsen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btnsen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        Btnsen.setText("Sen()");
        Btnsen.setBorder(null);
        Btnsen.setFocusPainted(false);
        Btnsen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btnsen.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        Btnsen.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btnsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsenActionPerformed(evt);
            }
        });

        BtnMult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnMult.setForeground(new java.awt.Color(255, 255, 255));
        BtnMult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn11.png"))); // NOI18N
        BtnMult.setText("X");
        BtnMult.setBorder(null);
        BtnMult.setFocusPainted(false);
        BtnMult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnMult.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn11.png"))); // NOI18N
        BtnMult.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        BtnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMultActionPerformed(evt);
            }
        });

        Btn3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn3.setForeground(new java.awt.Color(255, 255, 255));
        Btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn3.setText("3");
        Btn3.setBorder(null);
        Btn3.setFocusPainted(false);
        Btn3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        Btn4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn4.setForeground(new java.awt.Color(255, 255, 255));
        Btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn4.setText("4");
        Btn4.setBorder(null);
        Btn4.setFocusPainted(false);
        Btn4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        Btn9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn9.setForeground(new java.awt.Color(255, 255, 255));
        Btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn9.setText("9");
        Btn9.setBorder(null);
        Btn9.setFocusPainted(false);
        Btn9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });

        Btn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn2.setForeground(new java.awt.Color(255, 255, 255));
        Btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn2.setText("2");
        Btn2.setBorder(null);
        Btn2.setFocusPainted(false);
        Btn2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        Btn8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn8.setForeground(new java.awt.Color(255, 255, 255));
        Btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn8.setText("8");
        Btn8.setBorder(null);
        Btn8.setFocusPainted(false);
        Btn8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });

        Btn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn1.setForeground(new java.awt.Color(255, 255, 255));
        Btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn1.setText("1");
        Btn1.setBorder(null);
        Btn1.setFocusPainted(false);
        Btn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn5.setForeground(new java.awt.Color(255, 255, 255));
        Btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn5.setText("5");
        Btn5.setBorder(null);
        Btn5.setFocusPainted(false);
        Btn5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        BtnVersion2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnVersion2.setForeground(new java.awt.Color(255, 255, 255));
        BtnVersion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        BtnVersion2.setText("V2.0");
        BtnVersion2.setBorder(null);
        BtnVersion2.setFocusPainted(false);
        BtnVersion2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnVersion2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        BtnVersion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVersion2ActionPerformed(evt);
            }
        });

        Btn6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn6.setForeground(new java.awt.Color(255, 255, 255));
        Btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn6.setText("6");
        Btn6.setBorder(null);
        Btn6.setFocusPainted(false);
        Btn6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        Btn6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });

        BtnPow.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnPow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        BtnPow.setText("^");
        BtnPow.setBorder(null);
        BtnPow.setFocusPainted(false);
        BtnPow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPow.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        BtnPow.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        BtnPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPowActionPerformed(evt);
            }
        });

        Btntan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btntan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        Btntan.setText("Tan()");
        Btntan.setBorder(null);
        Btntan.setFocusPainted(false);
        Btntan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btntan.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        Btntan.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntanActionPerformed(evt);
            }
        });

        Btncos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btncos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        Btncos.setText("Cos()");
        Btncos.setBorder(null);
        Btncos.setFocusPainted(false);
        Btncos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btncos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn22.png"))); // NOI18N
        Btncos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        Btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtncosActionPerformed(evt);
            }
        });

        BtnPunto1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnPunto1.setForeground(new java.awt.Color(255, 255, 255));
        BtnPunto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        BtnPunto1.setText(".");
        BtnPunto1.setBorder(null);
        BtnPunto1.setFocusPainted(false);
        BtnPunto1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPunto1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btn33.png"))); // NOI18N
        BtnPunto1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesbtn/btnpress.png"))); // NOI18N
        BtnPunto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPunto1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnPow, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(BtnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnPunto1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BtnSuma)
                                            .addComponent(BtnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtsalidaop, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Btnsen, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btncos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btntan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnVersion2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnsen)
                    .addComponent(Btntan)
                    .addComponent(Btncos)
                    .addComponent(BtnVersion2))
                .addGap(18, 18, 18)
                .addComponent(txtsalidaop, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBorrar)
                    .addComponent(BtnRaiz)
                    .addComponent(BtnDiv)
                    .addComponent(BtnPow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn8)
                    .addComponent(Btn7)
                    .addComponent(Btn9)
                    .addComponent(BtnMult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn5)
                            .addComponent(Btn4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn3)
                            .addComponent(Btn2)
                            .addComponent(Btn1)
                            .addComponent(BtnSuma)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnResta)
                        .addComponent(Btn6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnIgual)
                    .addComponent(BtnPunto1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRaizActionPerformed
        addnumero("√");
        rta.raiz( txtsalida.getText());
    }//GEN-LAST:event_BtnRaizActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
        txtsalida.setText(addnumero("7"));  
        txtsalida.setText(rta.conect("7"));
    }//GEN-LAST:event_Btn7ActionPerformed

    private void BtnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSumaActionPerformed
        addnumero("+");
        rta.suma(txtsalida.getText());
    }//GEN-LAST:event_BtnSumaActionPerformed

    private void BtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRestaActionPerformed
        addnumero("-");
        rta.resta(txtsalida.getText());
    }//GEN-LAST:event_BtnRestaActionPerformed
  
    private void BtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIgualActionPerformed
        txtsalida.setText(""+ rta.result(txtsalida.getText()));
        // txt.setText(""+metodox.resultado(txt.getText()));
    }//GEN-LAST:event_BtnIgualActionPerformed

    private void BtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDivActionPerformed
        addnumero("/");
        rta.division(txtsalida.getText());    
    }//GEN-LAST:event_BtnDivActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        txtsalida.setText("");
        txtsalidaop.setText("");
        rta.borrar(txtsalida.getText());// TODO add your handling code here:
    }//GEN-LAST:event_BtnBorrarActionPerformed

    private void BtnsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsenActionPerformed
        addnumero("sen(");
        rta.sen(txtsalida.getText());     
    }//GEN-LAST:event_BtnsenActionPerformed

    private void BtnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMultActionPerformed
        addnumero("*");
        rta.multiplicacion(txtsalida.getText());  
    }//GEN-LAST:event_BtnMultActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        txtsalida.setText(addnumero("3"));   
        txtsalida.setText(rta.conect("3"));
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        txtsalida.setText(addnumero("4")); 
        txtsalida.setText(rta.conect("4"));
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        txtsalida.setText(addnumero("9")); 
        txtsalida.setText(rta.conect("9"));
    }//GEN-LAST:event_Btn9ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        txtsalida.setText(addnumero("2"));
        txtsalida.setText(rta.conect("2"));
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        txtsalida.setText(addnumero("8"));
        txtsalida.setText(rta.conect("8"));
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        txtsalida.setText(addnumero("1"));
        txtsalida.setText(rta.conect("1"));
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        txtsalida.setText(addnumero("5"));
        txtsalida.setText(rta.conect("5"));
    }//GEN-LAST:event_Btn5ActionPerformed

    private void BtnVersion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVersion2ActionPerformed
        txtsalida.setText(addnumero("Version2.0"));
        txtsalidaop.setText(rta.conect("SyntaxError"));
    }//GEN-LAST:event_BtnVersion2ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        txtsalida.setText(addnumero("6"));
        txtsalida.setText(rta.conect("6"));        
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        txtsalida.setText(addnumero("0"));  
        txtsalida.setText(rta.conect("0"));
    }//GEN-LAST:event_Btn0ActionPerformed

    private void BtnPowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPowActionPerformed
        addnumero("^");
        rta.pow(txtsalida.getText());// TODO add your handling code here:
    }//GEN-LAST:event_BtnPowActionPerformed

    private void BtntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntanActionPerformed
        addnumero("tan(");
        rta.tan(txtsalida.getText());
    }//GEN-LAST:event_BtntanActionPerformed

    private void BtncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtncosActionPerformed
        addnumero("cos(");
        rta.cos(txtsalida.getText());// TODO add your handling code here:
    }//GEN-LAST:event_BtncosActionPerformed

    private void BtnPunto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPunto1ActionPerformed
        txtsalida.setText(addnumero(".")); 
        txtsalida.setText(rta.conect("."));// TODO add your handling code here:
    }//GEN-LAST:event_BtnPunto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new interfaz().setVisible(true);
        });
    }
    public String addnumero(String digito){
        txtsalidaop.setText(txtsalidaop.getText()+digito);
        return digito;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnDiv;
    private javax.swing.JButton BtnIgual;
    private javax.swing.JButton BtnMult;
    private javax.swing.JButton BtnPow;
    private javax.swing.JButton BtnPunto1;
    private javax.swing.JButton BtnRaiz;
    private javax.swing.JButton BtnResta;
    private javax.swing.JButton BtnSuma;
    private javax.swing.JButton BtnVersion2;
    private javax.swing.JButton Btncos;
    private javax.swing.JButton Btnsen;
    private javax.swing.JButton Btntan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtsalida;
    private javax.swing.JLabel txtsalidaop;
    // End of variables declaration//GEN-END:variables

}